### PR TITLE
Added json to table plugin and properties page

### PR DESCRIPTION
**Pull request by ErdalDomi**
This commit adds a plugin to transform a JSON file from a url to a (nested) table. 

The plugin used is: https://www.npmjs.com/package/vue-json-to-table

properties.md was added under advanced, currently with an example JSON already loaded.

### CODE REVIEW

**Comment by bcogrel** [comment]
Thanks Erdal! I will give a look at it.

**Comment by bcogrel** [comment]
Hi @ErdalDomi , I started to work on a JSON file, see https://github.com/ontop/ontop-website/tree/feature/properties.

I experienced some limitations with the Vue component. The main issue is that it capitalizes the key, which would be confusing for users. In terms of rendering, I think that a regular table like https://ontop-vkg.org/guide/advanced/predefined.html#entries looks better.

How shall we proceed? Shall we write our own component?

Best,
Benjamin

**Comment by ErdalDomi** [comment]
Hi,

I also noticed limitations, for example, it is somehow unable to parse Boolean as a value and while it still works, it gives an error in the console message. 

I looked at the way the tables in https://ontop-vkg.org/guide/advanced/predefined.html#entries are built and it seems quite straightforward to plug in the values coming in from the JSON and populate the table while preserving the structure/style. 

Definitely the way to go is to create a re-usable component for this purpose. I will make a new pull request shortly.

Thanks,

**Comment by bcogrel** [comment]
Replaced by #21 .

**Pull request closed without merging**
